// frontend/src/components/DashboardItem.jsx
import React from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import { toast } from "react-toastify";

const DashboardItem = ({
  id,
  name,
  accountNumber,
  description,
  currentBalance,
}) => {
  const token = localStorage.getItem("token");
  axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;

  const deleteWallet = async () => {
    try {
      const response = await axios.delete(`http://localhost:8080/wallet/${id}`);
      if (response.status === 200) {
        console.log("DELETED");
        toast.warning(`${name} deleted`);
      }
    } catch (err) {
      console.log("Cannot delete wallet", err);
    }
  };

  return (
    <div className="container">
      <div className="card card-body bg-light mb-3 shadow">
        <div className="row">
          <div className="col-lg-4 col-md-3 col-6">
            <h3 className="font-weight-bold">{name}</h3>
            <p className="text-muted">Account Number: {accountNumber}</p>
            <p className="text-muted">{description}</p>
          </div>
          <div className="col-lg-4 col-md-3 col-6 text-center">
            <h3 className="font-weight-bold">Balance</h3>
            <h1 className="display-4">Rs. {currentBalance}</h1>
          </div>
          <div className="col-md-4 col-12 d-lg-block">
            <ul className="list-group list-group-flush">
              <li className="list-group-item mb-2">
                <Link
                  to={`/transactions/${id}`}
                  className="btn btn-sm btn-primary w-100"
                >
                  <i className="fas fa-list-alt pr-1"></i> View Transactions
                </Link>
              </li>
              <li className="list-group-item mb-2">
                <Link
                  to={`/updatewallet/${id}`}
                  className="btn btn-sm btn-info w-100"
                >
                  <i className="fas fa-edit pr-1"></i> Update Wallet Info
                </Link>
              </li>
              <li className="list-group-item">
                <button
                  className="btn btn-sm btn-danger w-100"
                  onClick={() => {
                    deleteWallet();
                  }}
                >
                  <i className="fas fa-trash-alt pr-1"></i> Delete Wallet
                </button>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardItem;

// frontend-angular/src/app/components/dashboard/dashboard-item/dashboard-item.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ToastService } from 'angular-toastify';
import { WalletsService } from '../../../services/wallets.service';

@Component({
  selector: 'app-dashboard-item',
  templateUrl: './dashboard-item.component.html',
  styleUrl: './dashboard-item.component.css',
})
export class DashboardItemComponent implements OnInit {
  @Input() wallet: any;
  @Output() walletDeleted = new EventEmitter<number>();

  constructor(
    private walletService: WalletsService,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    console.log(this.wallet);
  }

  deleteWallet(): void {
    if (confirm('Are you sure you want to delete this wallet?')) {
      this.walletService.deleteWallet(this.wallet.id).subscribe({
        next: (res) => {
          console.log(res);
          console.log(`Deleting wallet with ID: ${this.wallet.id}`);
          this.walletDeleted.emit(this.wallet.id);
          this.toast.warn('Wallet Deleted');
        },
        error: (e) => console.log(e),
      });
    }
  }
}

<div class="container">
  <div class="card card-body bg-light mb-3 shadow">
    <div class="row">
      <div class="col-lg-4 col-md-3 col-6">
        <h3 class="font-weight-bold">{{ wallet.name }}</h3>
        <p class="text-muted">Account Number: {{ wallet.accountNumber }}</p>
        <p class="text-muted">{{ wallet.description }}</p>
      </div>
      <div class="col-lg-4 col-md-3 col-6 text-center">
        <h3 class="font-weight-bold">Balance</h3>
        <h1 class="display-4">
          {{ wallet.currentBalance | currency : "INR" }}
        </h1>
      </div>
      <div class="col-md-4 col-12 d-lg-block">
        <ul class="list-group list-group-flush">
          <li class="list-group-item mb-2">
            <button
              class="btn btn-sm btn-primary w-100"
              [routerLink]="['/transactions/' + wallet.id]"
            >
              <i class="fas fa-list-alt pr-1"></i> View Transactions
            </button>
          </li>
          <li class="list-group-item mb-2">
            <button
              class="btn btn-sm btn-info w-100"
              [routerLink]="['/updatewallet/' + wallet.id]"
            >
              <i class="fas fa-arrow-circle-up pr-1"></i> Update Wallet Info
            </button>
          </li>

          <li class="list-group-item">
            <button
              class="btn btn-sm btn-danger w-100"
              (click)="deleteWallet()"
            >
              <i class="fas fa-trash pr-1"></i> Delete Wallet
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
