// frontend-angular/src/app/components/wallets/update-wallet/update-wallet.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ToastService } from 'angular-toastify';
import { WalletsService } from '../../../services/wallets.service';

@Component({
  selector: 'app-update-wallet',
  templateUrl: './update-wallet.component.html',
  styleUrl: './update-wallet.component.css',
})
export class UpdateWalletComponent implements OnInit {
  updateform: FormGroup;
  walletId: any;
  wallet: any = {};

  constructor(
    private router: Router,
    private walletService: WalletsService,
    formBuilder: FormBuilder,
    private route: ActivatedRoute,
    private toast: ToastService
  ) {
    this.updateform = formBuilder.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      accountNumber: [''],
      description: [''],
      currentBalance: [''],
    });
  }
  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      this.walletId = params.get('walletId');
    });
    this.walletService.getWalletById(this.walletId).subscribe({
      next: (res) => {
        console.log(res),
          (this.wallet = res),
          this.updateform.patchValue(this.wallet);
      },
      error: (e) => console.error(e),
    });
  }
  handleSubmit() {
    this.walletService
      .updateWallet(this.updateform.value, this.walletId)
      .subscribe({
        next: (res) => {
          console.log(res), this.toast.info('Wallet Updated');
        },
        error: (e) => console.error(e),
      });
  }
}

<app-navbar></app-navbar>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-6 m-auto">
      <button class="btn btn-light btn-sm mb-2" [routerLink]="['/dashboard']">
        <i class="fas fa-chevron-left"></i> Back to Dashboard
      </button>
      <h5 class="display-6 text-center mb-2">Update Wallet</h5>
      <hr class="my-4" />
      <form [formGroup]="updateform" (ngSubmit)="handleSubmit()">
        <div class="form-row">
          <div class="col-12 mb-2">
            <label>Account Name</label>
            <input
              type="text"
              class="form-control"
              id="name"
              formControlName="name"
            />
            @if ((updateform.controls['name'].invalid) &&
            (updateform.controls['name'].dirty ||
            updateform.controls['name'].touched)) {
            @if(updateform.controls['name'].hasError('required')) {
            <span class="text-danger">Name is cannot be empty!</span>
            } @if(updateform.controls['name'].hasError('minlength')) {
            <span class="text-danger">Minimum 2 characters long!</span>
            } }
          </div>
          <div class="col-12 mb-2">
            <label>Account No</label>
            <input
              type="text"
              class="form-control"
              id="accountNumber"
              formControlName="accountNumber"
            />
          </div>
          <div class="col-12 mb-2">
            <label>Description</label>
            <textarea
              class="form-control"
              id="description"
              formControlName="description"
            >
            </textarea>
          </div>
        </div>
        <div class="text-center mb-2">
          <button type="submit" class="btn btn-primary btn-block">
            Update
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// frontend/src/components/Wallets/UpdateWallet.jsx
import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useState } from "react";
import { useEffect } from "react";
import axios from "axios";
import NavBar from "../NavBar";
import { toast } from "react-toastify";

const UpdateWallet = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: "",
    accountNumber: "",
    description: "",
    currentBalance: "",
  });

  const changeHandler = (e, fieldName) => {
    setFormData({
      ...formData,
      [fieldName]: e.target.value,
    });
  };
  // const token = localStorage.getItem("token");
  // axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;
  const fetchWalletData = async () => {
    try {
      const response = await axios.get(`http://localhost:8080/wallet/${id}`);
      setFormData({
        name: response.data.name,
        accountNumber: response.data.accountNumber,
        description: response.data.description,
        currentBalance: response.data.currentBalance,
      });
    } catch (error) {
      console.log("Error fetching wallet data", error);
    }
  };

  useEffect(() => {
    fetchWalletData();
  }, []);

  const submitHandler = (e) => {
    e.preventDefault();
    setFormData((prevFormData) => ({
      ...prevFormData,
    }));
    axios
      .put(`http://localhost:8080/wallet/${id}`, formData)
      .then((response) => {
        console.log("Success with id", id);
        console.log(response.data);
        navigate("/dashboard");
        toast.info(`Wallet Info Updated`);
      })
      .catch((err) => {
        console.log("Cannot update wallet data", err);
      });
  };
  return (
    <>
      <NavBar />
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-8 col-lg-6 m-auto">
            <h5 className="display-4 text-center mb-2">Update Wallet</h5>
            <hr className="my-4" />
            <form onSubmit={(e) => submitHandler(e)}>
              <div className="form-row">
                <div className="col-12 mb-2">
                  <label>Account Name</label>
                  <input
                    type="text"
                    className="form-control"
                    id="name"
                    value={formData.name}
                    onChange={(e) => changeHandler(e, "name")}
                  />
                </div>
                <div className="col-12 mb-2">
                  <label>Account No</label>
                  <input
                    type="text"
                    className="form-control"
                    id="accountNumber"
                    value={formData.accountNumber}
                    onChange={(e) => changeHandler(e, "accountNumber")}
                  />
                </div>
                <div className="col-12 mb-2">
                  <label>Description</label>
                  <textarea
                    className="form-control"
                    id="description"
                    value={formData.description}
                    onChange={(e) => changeHandler(e, "description")}
                  />
                </div>
              </div>
              <div className="text-center mb-2">
                <button type="submit" className="btn btn-primary btn-block">
                  Update
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default UpdateWallet;
