// frontend/src/components/Wallets/CreateWallet.jsx
import React from "react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import NavBar from "../NavBar";
import { toast } from "react-toastify";

const CreateWallet = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: "",
    accountNumber: "",
    description: "",
    currentBalance: "",
  });

  const changeHandler = (e, fieldName) => {
    setFormData({
      ...formData,
      [fieldName]: e.target.value,
    });
  };

  const submitHandler = (e) => {
    e.preventDefault();
    setFormData((prevFormData) => ({
      ...prevFormData,
    }));
    const token = localStorage.getItem("token");
    axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;
    axios
      .post("http://localhost:8080/wallet", formData)
      .then((response) => {
        console.log("Success", response.data);
        navigate("/dashboard");
        toast.success(`${formData.name} wallet created`);
      })
      .catch((err) => {
        console.log("Cannot post wallet data", err);
      });
  };
  return (
    <>
      <NavBar />
      <div className="container">
        <div className="row">
          <div className="col-md-8 m-auto">
            <h5 className="display-4 text-center mb-4">Create Wallet</h5>
            <hr className="my-4" />
            <form onSubmit={(e) => submitHandler(e)}>
              <div className="form-group mb-3">
                <input
                  type="text"
                  className="form-control form-control-lg shadow border-radius-10"
                  placeholder="Wallet Name"
                  onChange={(e) => changeHandler(e, "name")}
                />
              </div>
              <div className="form-group mb-3">
                <input
                  type="text"
                  className="form-control form-control-lg shadow border-radius-10"
                  placeholder="Wallet Number"
                  onChange={(e) => changeHandler(e, "accountNumber")}
                />
              </div>
              <div className="form-group mb-3">
                <textarea
                  className="form-control form-control-lg shadow border-radius-10"
                  placeholder="Description"
                  onChange={(e) => changeHandler(e, "description")}
                ></textarea>
              </div>
              <div className="form-group mb-3">
                <input
                  type="number"
                  className="form-control form-control-lg shadow border-radius-10"
                  placeholder="Balance"
                  onChange={(e) => changeHandler(e, "currentBalance")}
                />
              </div>
              <div className="text-center">
                <button
                  type="submit"
                  className="btn btn-primary btn-block mt-4 shadow-lg border-radius-10"
                >
                  Create
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default CreateWallet;

// frontend-angular/src/app/components/wallets/create-wallet/create-wallet.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastService } from 'angular-toastify';
import { WalletsService } from '../../../services/wallets.service';

@Component({
  selector: 'app-create-wallet',
  templateUrl: './create-wallet.component.html',
  styleUrl: './create-wallet.component.css',
})
export class CreateWalletComponent {
  createWalletForm: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private walletService: WalletsService,
    private toast: ToastService
  ) {
    this.createWalletForm = this.formBuilder.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      accountNumber: [''],
      description: [''],
      currentBalance: [''],
    });
  }

  submitHandler() {
    this.walletService.createWallet(this.createWalletForm.value).subscribe({
      next: (response) => {
        console.log('Success', response);
        this.router.navigate(['/dashboard']);
        this.toast.info(`Wallet Created : ${response.name}`);
      },
      error: (err) => console.log('Cannot post wallet data', err),
    });
  }
}

<app-navbar></app-navbar>
<div class="container">
  <div class="row">
    <div class="col-md-6 m-auto">
      <button class="btn btn-light btn-sm mb-2" [routerLink]="['/dashboard']">
        <i class="fas fa-chevron-left"></i> Back to Dashboard
      </button>
      <h5 class="display-6 text-center mb-4">Create Wallet</h5>
      <hr class="my-4" />
      <form [formGroup]="createWalletForm" (ngSubmit)="submitHandler()">
        <div class="form-group mb-3">
          <input
            formControlName="name"
            type="text"
            class="form-control"
            placeholder="Wallet Name"
          />
          @if ((createWalletForm.controls['name'].invalid) &&
          (createWalletForm.controls['name'].dirty ||
          createWalletForm.controls['name'].touched)) {
          @if(createWalletForm.controls['name'].hasError('required')) {
          <span class="text-danger">Name is cannot be empty!</span>
          } @if(createWalletForm.controls['name'].hasError('minlength')) {
          <span class="text-danger">Minimum 2 characters long!</span>
          } }
        </div>
        <div class="form-group mb-3">
          <input
            formControlName="accountNumber"
            type="text"
            class="form-control"
            placeholder="Wallet Number"
          />
        </div>
        <div class="form-group mb-3">
          <textarea
            formControlName="description"
            class="form-control"
            placeholder="Description"
          ></textarea>
        </div>
        <div class="form-group mb-3">
          <input
            formControlName="currentBalance"
            type="number"
            class="form-control"
            placeholder="Balance"
          />
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary btn-block">
            Create
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
