// frontend/src/components/Transactions/AddTransaction.jsx
import React from "react";
import { Link, useParams } from "react-router-dom";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import NavBar from "../NavBar";
import { toast } from "react-toastify";

const AddTransaction = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [transaction, setTransaction] = useState({
    amount: "",
    description: "",
    transactionDate: "", // added transactionDate field
  });

  const changeHandler = (e, fieldName) => {
    setTransaction({
      ...transaction,
      [fieldName]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    console.log(transaction);
    try {
      const response = await axios.post(
        `http://localhost:8080/transaction/${id}`,
        transaction
      );
      if (response.status === 201) {
        console.log(response.data);
        navigate(`/transactions/${id}`);
        toast.success(`${transaction.description} added`);
      }
    } catch (err) {
      console.log("Cannot add transaction ", err);
    }
  };

  return (
    <>
      <NavBar />
      <div className="container py-5">
        <div className="row justify-content-center">
          <div className="col-md-8 col-lg-6 m-auto">
            <Link
              to={`/transactions/${id}`}
              className="btn btn-light btn-sm mb-2"
            >
              <i className="fas fa-chevron-left"></i> Back to Wallet
            </Link>
            <h4 className="display-4 text-center mb-3">
              Record New Transaction
            </h4>
            <form onSubmit={handleSubmit}>
              <div className="form-group mb-3">
                <input
                  type="number"
                  min="1"
                  name="amount"
                  value={transaction.amount}
                  onChange={(e) => changeHandler(e, "amount")}
                  className="form-control form-control-lg"
                  placeholder="Amount"
                />
              </div>
              <div className="form-group mb-3">
                <textarea
                  value={transaction.description}
                  name="description"
                  onChange={(e) => changeHandler(e, "description")}
                  className="form-control form-control-lg"
                  placeholder="Description"
                ></textarea>
              </div>
              <div className="form-group mb-3">
                <input
                  type="date"
                  name="transactionDate"
                  value={transaction.transactionDate}
                  onChange={(e) => changeHandler(e, "transactionDate")}
                  className="form-control form-control-lg"
                  placeholder="Transaction Date"
                />
              </div>
              <div className="text-center">
                <button className="btn btn-primary btn-lg">
                  Record Transaction
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default AddTransaction;

// frontend-angular/src/app/components/transactions/add-transaction/add-transaction.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { TransactionsService } from '../../../services/transactions.service';
import { ToastService } from 'angular-toastify';

@Component({
  selector: 'app-add-transaction',
  templateUrl: './add-transaction.component.html',
  styleUrls: ['./add-transaction.component.css'],
})
export class AddTransactionComponent implements OnInit {
  transactionForm: FormGroup;
  walletId: any;

  constructor(
    private formBuilder: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private transactionsService: TransactionsService,
    private toast: ToastService
  ) {
    this.transactionForm = this.formBuilder.group({
      amount: ['', [Validators.required, Validators.min(1)]],
      description: [''],
      transactionDate: [''],
    });
  }

  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      this.walletId = params.get('walletId');
    });
    console.log(this.walletId);
  }

  onSubmit(): void {
    console.log(this.transactionForm.value);
    this.transactionsService
      .addTransaction(this.transactionForm.value, this.walletId)
      .subscribe({
        next: (res) => {
          console.log(res), this.toast.info('Transaction Added');
        },
        error: (e) => console.log(e),
      });
  }
}

<app-navbar></app-navbar>
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6 m-auto">
      <button
        class="btn btn-light btn-sm mb-2"
        [routerLink]="['/transactions', walletId]"
      >
        <i class="fas fa-chevron-left"></i> Back to Wallet
      </button>
      <h4 class="display-4 text-center mb-3">Record New Transaction</h4>
      <form [formGroup]="transactionForm" (ngSubmit)="onSubmit()">
        <div class="form-group mb-3">
          <input
            type="number"
            min="1"
            formControlName="amount"
            class="form-control form-control-lg"
            placeholder="Amount"
          />
          @if ((transactionForm.controls['amount'].invalid) &&
          (transactionForm.controls['amount'].dirty ||
          transactionForm.controls['amount'].touched)) {
          @if(transactionForm.controls['amount'].hasError('required')) {
          <span class="text-danger">Amount is cannot be empty!</span>
          } @if(transactionForm.controls['amount'].hasError('min')) {
          <span class="text-danger">Minimum 1!</span>
          } }
        </div>
        <div class="form-group mb-3">
          <textarea
            formControlName="description"
            class="form-control form-control-lg"
            placeholder="Description"
          ></textarea>
        </div>
        <div class="form-group mb-3">
          <input
            type="date"
            formControlName="transactionDate"
            class="form-control form-control-lg"
            placeholder="Transaction Date"
          />
        </div>
        <div class="text-center">
          <button class="btn btn-primary btn-lg">Record Transaction</button>
        </div>
      </form>
    </div>
  </div>
</div>
