// frontend/src/components/authentication/Signup.jsx
import axios from "axios";
import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import { toast } from "react-toastify";

const Signup = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
  });

  const changeHandler = (e, fieldName) => {
    setFormData({
      ...formData,
      [fieldName]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormData((prevFormData) => ({
      ...prevFormData,
    }));
    console.log(formData);
    try {
      const response = await axios.post(
        "http://localhost:8080/auth/register",
        formData
      );
      if (response.status === 201) {
        console.log(response.data);
        navigate("/login");
        toast.success(`New user created:${formData.name}`);
      }
    } catch (err) {
      toast.error("User already exists");
    }
  };

  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-md-6">
          <div className="card shadow-lg border-0">
            <div className="card-body p-4">
              <h3 className="text-center mb-4">Register</h3>
              <form onSubmit={(e) => handleSubmit(e)}>
                <div className="form-group mb-3">
                  <label className="form-label" htmlFor="name">
                    Name
                  </label>
                  <input
                    type="text"
                    className="form-control form-control-lg"
                    id="name"
                    placeholder="Enter name"
                    required
                    onChange={(e) => changeHandler(e, "name")}
                  />
                </div>
                <div className="form-group mb-3">
                  <label className="form-label" htmlFor="email">
                    Email address
                  </label>
                  <input
                    type="email"
                    className="form-control form-control-lg"
                    id="email"
                    placeholder="Enter email"
                    required
                    onChange={(e) => changeHandler(e, "email")}
                  />
                </div>
                <div className="form-group mb-3">
                  <label className="form-label" htmlFor="password">
                    Password
                  </label>
                  <input
                    type="password"
                    className="form-control form-control-lg"
                    id="password"
                    placeholder="Enter password"
                    required
                    onChange={(e) => changeHandler(e, "password")}
                  />
                </div>
                <div className="text-center">
                  <button
                    type="submit"
                    className="btn btn-primary btn-lg btn-block"
                  >
                    Sign Up
                  </button>
                </div>
                <p className="text-center mt-3">
                  Already registered? <Link to="/login">Sign in</Link>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Signup;

// frontend-angular/src/app/components/authentication/signup/signup.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastService } from 'angular-toastify';
import { AuthenticationService } from '../../../services/authentication.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.css',
})
export class SignupComponent {
  signupForm: FormGroup;

  constructor(
    private router: Router,
    formBuilder: FormBuilder,
    private authService: AuthenticationService,
    private toast: ToastService
  ) {
    this.signupForm = formBuilder.group({
      name: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(5)]],
    });
  }

  handleSubmit() {
    if (this.signupForm.valid) {
      this.authService.registerUser(this.signupForm.value).subscribe({
        next: (response) => {
          console.log(response),
            this.toast.success('Register Successful'),
            this.router.navigate(['/login']);
        },
        error: (e) => {
          console.error(e);
          this.toast.error('User Already Registered');
        },
        complete: () => console.info('complete'),
      });
    } else {
      this.toast.warn('Form is Invalid');
      console.log('Form is Invalid');
    }
  }
}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg border-0">
        <div class="card-body p-4">
          <h3 class="text-center mb-4">Register</h3>
          <form [formGroup]="signupForm" (ngSubmit)="handleSubmit()">
            <div class="form-group mb-3">
              <label class="form-label" for="name">Name</label>
              <input
                type="text"
                class="form-control form-control-lg"
                id="name"
                placeholder="Enter name"
                name="name"
                formControlName="name"
              />
            </div>
            @if ((signupForm.controls['name'].invalid) &&
            (signupForm.controls['name'].dirty ||
            signupForm.controls['name'].touched)) {
            @if(signupForm.controls['name'].hasError('required')) {
            <span class="text-danger">Name is cannot be empty!</span>
            } @if(signupForm.controls['name'].hasError('minlength')) {
            <span class="text-danger"
              >Name is must be at least 3 characters long!</span
            >
            } }

            <div class="form-group mb-3">
              <label class="form-label" for="email">Email address</label>
              <input
                type="email"
                class="form-control form-control-lg"
                id="email"
                placeholder="Enter email"
                name="email"
                formControlName="email"
              />
            </div>
            @if ((signupForm.controls['email'].invalid) &&
            (signupForm.controls['email'].dirty ||
            signupForm.controls['email'].touched)) {
            @if(signupForm.controls['email'].hasError('required')) {
            <span class="text-danger">Email is cannot be empty!</span>
            } @if(signupForm.controls['email'].hasError('email')) {
            <span class="text-danger">Enter a valid email!</span>
            } }
            <div class="form-group mb-3">
              <label class="form-label" for="password">Password</label>
              <input
                type="password"
                class="form-control form-control-lg"
                id="password"
                placeholder="Enter password"
                name="password"
                formControlName="password"
              />
              @if ((signupForm.controls['password'].invalid) &&
              (signupForm.controls['password'].dirty ||
              signupForm.controls['password'].touched)) {
              @if(signupForm.controls['password'].hasError('required')) {
              <span class="text-danger">Password is cannot be empty!</span>
              } @if(signupForm.controls['password'].hasError('minlength')) {
              <span class="text-danger"
                >Password must be at least 5 characters!</span
              >
              } }
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary btn-lg btn-block">
                Sign Up
              </button>
            </div>
            <p class="text-center mt-3">
              Already registered? <a routerLink="/login">Sign in</a>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
