// frontend-angular/src/app/components/authentication/edit-profile/edit-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastService } from 'angular-toastify';
import { UserService } from '../../../services/user.service';

@Component({
  selector: 'app-edit-profile',
  templateUrl: './edit-profile.component.html',
  styleUrl: './edit-profile.component.css',
})
export class EditProfileComponent implements OnInit {
  editUserForm: FormGroup;
  constructor(
    private router: Router,
    formBuilder: FormBuilder,
    private userService: UserService,
    private toast: ToastService
  ) {
    this.editUserForm = formBuilder.group({
      name: [''],
      email: [''],
      password: [''],
    });
  }
  ngOnInit(): void {
    this.userService.getUser().subscribe({
      next: (res) => {
        console.log(res);
        this.editUserForm.patchValue(res);
      },
    });
  }

  updateUser() {
    this.userService.editUser(this.editUserForm.value).subscribe({
      next: (res) => {
        console.log(res), this.toast.info('User Updated');
      },
      error: (e) => console.error(e),
    });
  }
}

<app-navbar></app-navbar>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6 m-auto">
      <button class="btn btn-light btn-sm mb-2" [routerLink]="['/dashboard']">
        <i class="fas fa-chevron-left"></i> Back to Dashboard
      </button>
      <h5 class="display-4 text-center mb-2">Update Profile</h5>
      <hr class="my-4" />
      <form [formGroup]="editUserForm" (ngSubmit)="updateUser()">
        <div class="form-row">
          <div class="col-12 mb-2">
            <label>Username</label>
            <input type="text" class="form-control" formControlName="name" />
          </div>
          <div class="col-12 mb-2">
            <label>Email</label>
            <input type="email" class="form-control" formControlName="email" />
          </div>
          <div class="col-12 mb-2">
            <label>Password</label>
            <input
              type="password"
              formControlName="password"
              class="form-control"
              placeholder="Enter new password"
              formControlName="password"
            />
          </div>
        </div>
        <div class="text-center mb-2">
          <button type="submit" class="btn btn-primary btn-block">
            Update
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// frontend/src/components/Profile/EditProfile.jsx
import axios from "axios";
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import NavBar from "../NavBar";

const EditProfile = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
  });

  useEffect(() => {
    const fetchProfile = async () => {
      try {
        const response = await axios.get(`http://localhost:8080/auth/profile`);
        if (response.status === 200) {
          setFormData({
            name: response.data.name,
            email: response.data.email,
            password: "",
          });
        }
      } catch (err) {
        console.error("Cannot fetch profile", err);
      }
    };
    fetchProfile();
  }, []);

  const changeHandler = (e, field) => {
    setFormData({ ...formData, [field]: e.target.value });
  };

  const submitHandler = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.put(
        `http://localhost:8080/auth/profile`,
        formData
      );
      if (response.status === 200) {
        console.log(response.data);
        navigate("/dashboard");
        toast.success("Successfully Updated");
      }
    } catch (err) {
      console.error("Cannot update wallet", err);
    }
  };

  return (
    <>
      <NavBar />
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-8 col-lg-6 m-auto">
            <h5 className="display-4 text-center mb-2">Update Profile</h5>
            <hr className="my-4" />
            <form onSubmit={submitHandler}>
              <div className="form-row">
                <div className="col-12 mb-2">
                  <label>Username</label>
                  <input
                    type="text"
                    className="form-control"
                    id="name"
                    value={formData.name}
                    onChange={(e) => changeHandler(e, "name")}
                  />
                </div>
                <div className="col-12 mb-2">
                  <label>Email</label>
                  <input
                    type="email"
                    className="form-control"
                    id="email"
                    value={formData.email}
                    onChange={(e) => changeHandler(e, "email")}
                  />
                </div>
                <div className="col-12 mb-2">
                  <label>Password</label>
                  <input
                    type="password"
                    className="form-control"
                    id="password"
                    value={formData.password}
                    onChange={(e) => changeHandler(e, "password")}
                    placeholder="Enter new password"
                  />
                </div>
              </div>
              <div className="text-center mb-2">
                <button type="submit" className="btn btn-primary btn-block">
                  Update
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default EditProfile;
