// frontend-angular/src/app/components/authentication/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ToastService } from 'angular-toastify';
import { AuthenticationService } from '../../../services/authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  loginForm: FormGroup;

  constructor(
    private router: Router,
    formBuilder: FormBuilder,
    private authService: AuthenticationService,
    private toast: ToastService
  ) {
    this.loginForm = formBuilder.group({
      email: [''],
      password: [''],
    });
  }

  onSubmit() {
    if (this.loginForm.valid) {
      console.log(this.loginForm);
      this.authService.loginUser(this.loginForm.value).subscribe({
        next: (response) => {
          console.log(response);
          this.toast.success(`Login Successful}`);
          localStorage.setItem('token', response.jwtToken);
          this.router.navigateByUrl('/dashboard');
        },
        error: (e) => {
          console.error(e), this.toast.error('User not found');
        },
        complete: () => console.info('complete'),
      });
    } else {
      console.log('Form is Invalid');
    }
  }
}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card shadow-lg border-0">
        <div class="card-body p-4">
          <h3 class="text-center mb-4">Sign In</h3>
          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <div class="form-group mb-3">
              <label class="form-label" for="email">Email address</label>
              <input
                type="email"
                class="form-control form-control-lg"
                id="email"
                placeholder="Enter email"
                name="email"
                formControlName="email"
              />
              @if ((loginForm.controls['email'].invalid) &&
              (loginForm.controls['email'].dirty ||
              loginForm.controls['email'].touched)) {
              @if(loginForm.controls['email'].hasError('required')) {
              <span class="text-danger">Email is cannot be empty!</span>
              } @if(loginForm.controls['email'].hasError('email')) {
              <span class="text-danger">Enter a valid email!</span>
              } }
            </div>
            <div class="form-group mb-3">
              <label class="form-label" for="password">Password</label>
              <input
                type="password"
                class="form-control form-control-lg"
                id="password"
                placeholder="Enter password"
                name="password"
                formControlName="password"
              />
              @if((loginForm.controls['password'].invalid) &&
              (loginForm.controls['password'].dirty ||
              loginForm.controls['password'].touched)) {
              @if(loginForm.controls['password'].hasError('required')) {
              <span class="text-danger">Password is cannot be empty!</span>
              } @if(loginForm.controls['password'].hasError('minlength')) {
              <span class="text-danger"
                >Password must be at least 5 characters!</span
              >
              } }
            </div>
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary btn-lg btn-block">
                Submit
              </button>
            </div>
            <div class="text-center mt-3">
              Not registered?
              <a routerLink="/register" class="text-decoration-none"
                >Register now</a
              >
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/authentication/Login.jsx
import React from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { useState } from "react";
import { toast } from "react-toastify";

const Login = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const changeHandler = (e, fieldName) => {
    setFormData({
      ...formData,
      [fieldName]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post(
        "http://localhost:8080/auth/login",
        formData
      );
      if (response.status === 200) {
        console.log(response.data);
        localStorage.setItem("token", response.data.jwtToken);
        toast.success(`Successfully Logged in`);
        navigate("/dashboard");
      }
    } catch (err) {
      console.log("Login Unsuccessful", err);
    }
  };
  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-md-4">
          <div className="card shadow-lg border-0">
            <div className="card-body p-4">
              <h3 className="text-center mb-4">Sign In</h3>
              <form onSubmit={(e) => handleSubmit(e)}>
                <div className="form-group mb-3">
                  <label className="form-label" htmlFor="email">
                    Email address
                  </label>
                  <input
                    type="email"
                    className="form-control form-control-lg"
                    id="email"
                    placeholder="Enter email"
                    onChange={(e) => changeHandler(e, "email")}
                  />
                </div>
                <div className="form-group mb-3">
                  <label className="form-label" htmlFor="password">
                    Password
                  </label>
                  <input
                    type="password"
                    className="form-control form-control-lg"
                    id="password"
                    placeholder="Enter password"
                    onChange={(e) => changeHandler(e, "password")}
                  />
                </div>
                <div className="d-grid gap-2">
                  <button
                    type="submit"
                    className="btn btn-primary btn-lg btn-block"
                  >
                    Submit
                  </button>
                </div>
                <div className="text-center mt-3">
                  Not registered?{" "}
                  <Link to={"/register"} className="text-decoration-none">
                    Register now
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
